yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('posts/<int:post_id>/', include('posts.urls', namespace='posts')),
    path('posts/<int:post_id>/edit/', include('posts.urls',
                                              namespace='posts')),
    path('create/', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )

    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author',),
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


# Добавить поле image в форму
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Введите текст')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from .models import Post, Group, User, Follow
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.views.decorators.cache import cache_page


@cache_page(20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(posts, settings.NUM_OF_DISPLAYED_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    posts = (Post.objects.filter(group=group).
             order_by('-pub_date'))
    paginator = Paginator(posts, settings.NUM_OF_DISPLAYED_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = (Post.objects.filter(author=author).
             order_by('-pub_date'))
    paginator = Paginator(posts, settings.NUM_OF_DISPLAYED_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_num = posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'post_num': post_num,
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    post_num = (Post.objects.filter(author=author).count())
    comments = post.comments.all()
    comment_form = CommentForm(request.POST or None)
    context = {
        'post_num': post_num,
        'post': post,
        'comments': comments,
        'form': comment_form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            user = request.user
            form.instance.author = user
            form.save()
            return redirect('posts:profile', user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = post.author
    if user == request.user:
        if request.method == 'POST':
            form = PostForm(
                request.POST,
                files=request.FILES or None,
                instance=post)
            if form.is_valid():
                form.save()
                return redirect('posts:post_detail', post_id)
            return render(request, 'posts/create_post.html', {'form': form,
                          'is_edit': True, 'post_id': post_id})
        form = PostForm()
        return render(request, 'posts/create_post.html', {'form': form,
                      'is_edit': True, 'post_id': post_id})
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    # Получите пост и сохраните его в переменную post.
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, settings.NUM_OF_DISPLAYED_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        if not Follow.objects.filter(user=user, author=author).exists():
            Follow.objects.create(
                user=user,
                author=author
            )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    user = request.user
    Follow.objects.filter(user=user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title%} <title>Новый пост</title> {% endblock %}
{% block content%}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header"> 
                {% if is_edit %}
                  Редактировать запись 
                {% else %}      
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">
                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                {% endif %}
                    {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value={{ group.pk }} {{ form.group }} </option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div> 
                  <div class="form-group row my-3 p-3">
                    <label for="id_picture">
                    Картинка                  
                    </label>
                    {{ form.image }}                
                    <small id="id_picture-help" class="form-text text-muted">
                    Картинка нового поста
                    </small>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    {%endblock%}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title%} <title> Посты любимых авторов </title> {% endblock %}
    {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        {% include 'posts/includes/switcher.html' %} 
        <h1> Посты любимых авторов </h1>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %} 
          <p>{{ post.text }}</p>    
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif%}
          <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация </a></p>
        </article>
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
      </div>  
      {% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title%} <title> Группа {{group.title}}</title>{% endblock %}
    {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{group.description}}
        </p>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{post.author.get_full_name}}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}       
            <p>
              {{post.text}}
            </p>
          </article>
          <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация </a></p>         
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}
      </div>  
    {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title%} <title> Последние обновления на сайте </title> {% endblock %}
    {% block content %} 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        {% include 'posts/includes/switcher.html' %} 
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %} 
          <p>{{ post.text }}</p>    
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif%}
          <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация </a></p>
        </article>
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
      </div>  
      {% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
    {% load user_filters %}
    {% block title %}<title>Пост {{post.text|truncatechars:30}}</title>{% endblock %}
    {% block content %}
      {% load thumbnail %} 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{post.pub_date}} 
            </li>
            <!-- если у поста есть группа -->  
            {% if post.group %} 
            <li class="list-group-item">
              Группа: {{post.group.title}}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{post.author.get_full_name}}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{post_num}}</span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
            <p> {{post.text}} </p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %} 
        {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}"> 
            Pедактировать запись 
          </a>
        {% endif %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
              <div class="media mb-4">
                <div class="media-body">
                  <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                      {{ comment.author.username }}
                    </a>
                  </h5>
                  <p>
                    {{ comment.text }}
                  </p>
                </div>
              </div>
          {% endfor %}
        </article>
      </div> 
    {%endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
    {% block title %}<title>Профайл пользователя {{author}}</title>{% endblock %}
    {% block content %}
        <div class="mb-5">        
        <h1>Все посты пользователя {{author}} </h1>
        <h3>Всего постов: {{post_num}} </h3>   
        {% if following %}
            <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
            Отписаться
            </a>
        {% else %}
            <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
                Подписаться
            </a>
        {% endif %}
        </div>
        <div class="container py-5">   
        {% for post in page_obj %}
            <article>
            <ul>
                <li>
                Автор: {{author}}
                <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %} 
            <p>
                {{post.text}}
            </p>
            </article>
            <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация </a></p>
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif%}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}       
      </div>
    {%endblock%}